# a = Array2D(1, 2)
# arr = np.array([[1], [2]])
# b = np.array([[1, 2, 3], [4, 5, 6]])
# print(b)
# print(a)
# print((a + b)[0][0])
# print(b + a)
# print(type((b + a)[0][0][0]))
# print(b + arr)
# print(arr + b)
# print(0.5 + a)
# print(a + a)
# print(a + 0.5)

# print()
# print(a - 1)
# print(1 - a)
# print(a - a)
# print()
# print(a**2)
# print()
# print(2 * a)
# print(a * 2)
# print(a * a)


# # v = PointVectorGroup2D()
# arr = Array2D(1, 2)
# # print(arr.__to_np())
# print(arr)
